<?php

return [
    'industries' => [
        // Food & beverage
        'food',
        'restaurant',
        'cafe',
        'bar_nightlife',
        'bakery',
        'catering',
        'food_truck',
        'brewery_winery',
        // Retail & commerce
        'shop',
        'retail',
        'ecommerce',
        'groceries',
        'convenience_store',
        'fashion_apparel',
        'jewelry',
        'electronics',
        'furniture',
        'hardware',
        'bookstore',
        'florist',
        'sporting_goods',
        'toys_games',
        'automotive_parts',
        'pawn_consignment',
        // Health & wellness
        'healthcare',
        'pharmacy',
        'dental',
        'mental_health',
        'veterinary',
        'fitness',
        'spa_massage',
        'beauty',
        'salon_barbershop',
        'medical_lab',
        'home_health',
        // Professional & business services
        'professional',
        'consulting',
        'legal',
        'accounting',
        'finance_insurance',
        'marketing_advertising',
        'staffing_recruiting',
        'printing_signage',
        'translation_interpretation',
        // Technology & digital
        'technology',
        'software',
        'web_development',
        'mobile_app_development',
        'it_services',
        'telecommunications',
        'cybersecurity',
        'data_analytics',
        'saas',
        'cloud_computing',
        'ai_machine_learning',
        'hardware_technology',
        'electronics_repair',
        // Creative & media
        'design_creative',
        'photography_video',
        'media_publishing',
        'music_audio',
        'art_gallery',
        'events_weddings',
        'film_production',
        // Construction, home & trades
        'construction',
        'architecture',
        'engineering',
        'interior_design',
        'plumbing',
        'electrical',
        'hvac',
        'roofing',
        'landscaping',
        'home_garden',
        'cleaning_services',
        'pest_control',
        'pool_spa_services',
        'home_inspection',
        // Real estate & property
        'real_estate',
        'property_management',
        'coworking',
        'storage_moving',
        // Transportation, automotive & travel
        'automotive',
        'auto_repair',
        'car_dealer',
        'car_rental',
        'logistics_transportation',
        'delivery_courier',
        'travel_agency',
        'hospitality',
        'hotel_lodging',
        'airline_aviation',
        'maritime',
        // Education, training & childcare
        'education',
        'tutoring',
        'childcare',
        'training_coaching',
        'driving_school',
        // Entertainment & recreation
        'entertainment',
        'sports_recreation',
        'outdoor_adventure',
        'gaming',
        'amusement_attractions',
        // Industrial, agriculture & energy
        'manufacturing',
        'wholesale',
        'agriculture',
        'farming_ranching',
        'energy_utilities',
        'mining_resources',
        'scientific_research',
        'biotechnology',
        'environmental_services',
        // Community, nonprofit & public
        'nonprofit',
        'government',
        'religious',
        'community_organization',
        'social_services',
        'senior_care',
        'political_organization',
        // Personal & specialty services
        'pet_services',
        'security_services',
        'waste_recycling',
        'tailoring_alterations',
        'tattoo_piercing',
        'funeral_memorial',
        'notary_services',
        'services',
        'other',
    ],

    'industry_labels' => [
        'food' => 'Food & Drink',
        'restaurant' => 'Restaurant',
        'cafe' => 'Cafe & Coffee Shop',
        'bar_nightlife' => 'Bar & Nightlife',
        'bakery' => 'Bakery & Desserts',
        'catering' => 'Catering',
        'food_truck' => 'Food Truck & Street Food',
        'brewery_winery' => 'Brewery, Winery & Distillery',
        'shop' => 'Shop',
        'retail' => 'Retail Store',
        'ecommerce' => 'E-commerce & Online Store',
        'groceries' => 'Groceries & Supermarket',
        'convenience_store' => 'Convenience Store',
        'fashion_apparel' => 'Fashion & Apparel',
        'jewelry' => 'Jewelry & Watches',
        'electronics' => 'Electronics & Gadgets',
        'furniture' => 'Furniture & Home Goods',
        'hardware' => 'Hardware & Home Improvement',
        'bookstore' => 'Bookstore & Stationery',
        'florist' => 'Florist & Garden Center',
        'sporting_goods' => 'Sporting Goods',
        'toys_games' => 'Toys & Games',
        'automotive_parts' => 'Auto Parts & Accessories',
        'pawn_consignment' => 'Pawn Shop & Consignment',
        'healthcare' => 'Healthcare & Medical',
        'pharmacy' => 'Pharmacy',
        'dental' => 'Dental',
        'mental_health' => 'Mental Health & Counseling',
        'veterinary' => 'Veterinary & Animal Hospital',
        'fitness' => 'Fitness & Gym',
        'spa_massage' => 'Spa & Massage',
        'beauty' => 'Beauty & Wellness',
        'salon_barbershop' => 'Salon & Barbershop',
        'medical_lab' => 'Medical Lab & Diagnostics',
        'home_health' => 'Home Health & Caregiving',
        'professional' => 'Professional Services',
        'consulting' => 'Consulting',
        'legal' => 'Legal Services',
        'accounting' => 'Accounting & Bookkeeping',
        'finance_insurance' => 'Finance & Insurance',
        'marketing_advertising' => 'Marketing & Advertising',
        'staffing_recruiting' => 'Staffing & Recruiting',
        'printing_signage' => 'Printing & Signage',
        'translation_interpretation' => 'Translation & Interpretation',
        'technology' => 'Technology',
        'software' => 'Software Company',
        'web_development' => 'Web Development',
        'mobile_app_development' => 'Mobile App Development',
        'it_services' => 'IT Services & Support',
        'telecommunications' => 'Telecommunications',
        'cybersecurity' => 'Cybersecurity',
        'data_analytics' => 'Data & Analytics',
        'saas' => 'SaaS & Cloud Software',
        'cloud_computing' => 'Cloud Computing',
        'ai_machine_learning' => 'AI & Machine Learning',
        'hardware_technology' => 'Hardware & Devices',
        'electronics_repair' => 'Electronics Repair',
        'design_creative' => 'Design & Creative Agency',
        'photography_video' => 'Photography & Video',
        'media_publishing' => 'Media & Publishing',
        'music_audio' => 'Music & Audio Production',
        'art_gallery' => 'Art Gallery & Studio',
        'events_weddings' => 'Events & Weddings',
        'film_production' => 'Film & Video Production',
        'construction' => 'Construction & Contracting',
        'architecture' => 'Architecture',
        'engineering' => 'Engineering',
        'interior_design' => 'Interior Design',
        'plumbing' => 'Plumbing',
        'electrical' => 'Electrical',
        'hvac' => 'HVAC',
        'roofing' => 'Roofing',
        'landscaping' => 'Landscaping & Lawn Care',
        'home_garden' => 'Home & Garden',
        'cleaning_services' => 'Cleaning & Janitorial',
        'pest_control' => 'Pest Control',
        'pool_spa_services' => 'Pool & Spa Services',
        'home_inspection' => 'Home Inspection',
        'real_estate' => 'Real Estate',
        'property_management' => 'Property Management',
        'coworking' => 'Coworking & Office Space',
        'storage_moving' => 'Storage & Moving',
        'automotive' => 'Automotive',
        'auto_repair' => 'Auto Repair & Body Shop',
        'car_dealer' => 'Car Dealer',
        'car_rental' => 'Car Rental',
        'logistics_transportation' => 'Logistics & Transportation',
        'delivery_courier' => 'Delivery & Courier',
        'travel_agency' => 'Travel Agency',
        'hospitality' => 'Travel & Hospitality',
        'hotel_lodging' => 'Hotel & Lodging',
        'airline_aviation' => 'Airline & Aviation',
        'maritime' => 'Maritime & Boating',
        'education' => 'Education & School',
        'tutoring' => 'Tutoring & Test Prep',
        'childcare' => 'Childcare & Daycare',
        'training_coaching' => 'Training & Coaching',
        'driving_school' => 'Driving School',
        'entertainment' => 'Entertainment',
        'sports_recreation' => 'Sports & Recreation',
        'outdoor_adventure' => 'Outdoor & Adventure',
        'gaming' => 'Gaming & Esports',
        'amusement_attractions' => 'Amusement & Attractions',
        'manufacturing' => 'Manufacturing',
        'wholesale' => 'Wholesale & Distribution',
        'agriculture' => 'Agriculture',
        'farming_ranching' => 'Farming & Ranching',
        'energy_utilities' => 'Energy & Utilities',
        'mining_resources' => 'Mining & Natural Resources',
        'scientific_research' => 'Scientific Research',
        'biotechnology' => 'Biotechnology',
        'environmental_services' => 'Environmental Services',
        'nonprofit' => 'Nonprofit & Charity',
        'government' => 'Government & Public Sector',
        'religious' => 'Religious Organization',
        'community_organization' => 'Community Organization',
        'social_services' => 'Social Services',
        'senior_care' => 'Senior Care & Assisted Living',
        'political_organization' => 'Political Organization',
        'pet_services' => 'Pet Services & Supplies',
        'security_services' => 'Security Services',
        'waste_recycling' => 'Waste Management & Recycling',
        'tailoring_alterations' => 'Tailoring & Alterations',
        'tattoo_piercing' => 'Tattoo & Piercing',
        'funeral_memorial' => 'Funeral & Memorial',
        'notary_services' => 'Notary & Legal Support',
        'services' => 'General Services',
        'other' => 'Other',
    ],
];
