import type { ChatLabel, ChatList, ChatMessage, ChatRecord } from './types';

export const INITIAL_LABELS: ChatLabel[] = [
  { id: 'work', name: 'Work', color: '#1B00D8' },
  { id: 'family', name: 'Family', color: '#00b8ff' },
  { id: 'urgent', name: 'Urgent', color: '#ff0055' },
];

export const INITIAL_LISTS: ChatList[] = [
  { id: 'work', name: 'Work', chatIds: ['design-team', 'sofia'], muted: false },
  { id: 'friends', name: 'Friends', chatIds: ['weekend-trip', 'noah'], muted: false },
];

export const INITIAL_CHATS: ChatRecord[] = [
  {
    id: 'bella-napoli-chat',
    name: 'Bella Napoli',
    avatarLabel: 'BN',
    avatarColor: '#c45c26',
    preview: 'Your order is being prepared',
    dateLabel: '8/8/26',
    lastActivityAt: Date.now() - 3600000,
    unreadCount: 0,
    pinned: false,
    archived: false,
    muted: false,
    blocked: false,
    locked: false,
    hidden: false,
    favorite: false,
    markedUnread: false,
    isGroup: false,
    isBusiness: true,
    isSecret: false,
    listIds: [],
    labelIds: [],
  },
  {
    id: 'liam',
    name: 'Liam Becker',
    avatarLabel: 'LB',
    avatarColor: '#5b8def',
    preview: 'Anytime! Ship it 🚀',
    dateLabel: '8/8/26',
    lastActivityAt: Date.now() - 7200000,
    unreadCount: 0,
    pinned: true,
    archived: false,
    muted: false,
    blocked: false,
    locked: false,
    hidden: false,
    favorite: true,
    markedUnread: false,
    isGroup: false,
    isBusiness: false,
    isSecret: false,
    listIds: [],
    labelIds: ['work'],
  },
  {
    id: 'design-team',
    name: 'Design Team',
    avatarLabel: 'DT',
    avatarColor: '#7c6cf0',
    preview: 'Final mockups are in the shared folder 👍',
    dateLabel: '8/7/26',
    lastActivityAt: Date.now() - 86400000,
    unreadCount: 4,
    pinned: true,
    archived: false,
    muted: false,
    blocked: false,
    locked: false,
    hidden: false,
    favorite: false,
    markedUnread: false,
    isGroup: true,
    groupCount: 4,
    isBusiness: false,
    isSecret: false,
    listIds: ['work'],
    labelIds: ['work', 'urgent'],
  },
  {
    id: 'sofia',
    name: 'Sofia Martinez',
    avatarLabel: 'SM',
    avatarColor: '#e07a5f',
    preview: 'Can you review the deck before tomorrow?',
    dateLabel: '8/6/26',
    lastActivityAt: Date.now() - 172800000,
    unreadCount: 2,
    pinned: false,
    archived: false,
    muted: false,
    blocked: false,
    locked: false,
    hidden: false,
    favorite: false,
    markedUnread: false,
    isGroup: false,
    isBusiness: false,
    isSecret: false,
    listIds: ['work'],
    labelIds: ['urgent'],
  },
  {
    id: 'weekend-trip',
    name: 'Weekend Trip',
    avatarLabel: 'WT',
    avatarColor: '#3d9a8b',
    preview: 'Who is bringing snacks for Saturday? 🏔️',
    dateLabel: '8/5/26',
    lastActivityAt: Date.now() - 259200000,
    unreadCount: 3,
    pinned: false,
    archived: false,
    muted: true,
    muteUntil: null,
    blocked: false,
    locked: false,
    hidden: false,
    favorite: false,
    markedUnread: false,
    isGroup: true,
    groupCount: 6,
    isBusiness: false,
    isSecret: false,
    listIds: ['friends'],
    labelIds: ['family'],
  },
  {
    id: 'noah',
    name: 'Noah Park',
    avatarLabel: 'NP',
    avatarColor: '#f4a261',
    preview: 'Game night Friday?',
    dateLabel: '8/4/26',
    lastActivityAt: Date.now() - 345600000,
    unreadCount: 0,
    pinned: false,
    archived: false,
    muted: false,
    blocked: false,
    locked: false,
    hidden: true,
    favorite: false,
    markedUnread: false,
    isGroup: false,
    isBusiness: false,
    isSecret: false,
    listIds: ['friends'],
    labelIds: [],
  },
  {
    id: 'aria',
    name: 'Aria Chen',
    avatarLabel: 'AC',
    avatarColor: '#9b5de5',
    preview: "Loved the demo. Let's sync next week 🎉",
    dateLabel: '8/3/26',
    lastActivityAt: Date.now() - 432000000,
    unreadCount: 0,
    pinned: false,
    archived: true,
    muted: false,
    blocked: false,
    locked: false,
    hidden: false,
    favorite: false,
    markedUnread: false,
    isGroup: false,
    isBusiness: false,
    isSecret: false,
    listIds: [],
    labelIds: [],
  },
];

export const INITIAL_MESSAGES: Record<string, ChatMessage[]> = {
  liam: [
    {
      id: '1',
      type: 'text',
      text: 'Thanks for the review 🙏',
      sentAt: '2:14 AM',
      isOutgoing: false,
    },
    {
      id: '2',
      type: 'text',
      text: 'Anytime! Ship it 🚀',
      sentAt: '2:14 AM',
      isOutgoing: true,
      status: 'read',
    },
  ],
  sofia: [
    {
      id: '1',
      type: 'text',
      text: 'Can you review the deck before tomorrow?',
      sentAt: '9:02 AM',
      isOutgoing: false,
    },
    {
      id: '2',
      type: 'text',
      text: 'Coffee at 10am still works?',
      sentAt: '9:03 AM',
      isOutgoing: false,
    },
  ],
  'design-team': [
    {
      id: '1',
      type: 'sticker',
      stickerKey: 'rocket',
      sentAt: '11:20 AM',
      isOutgoing: false,
    },
    {
      id: '2',
      type: 'voice',
      durationSec: 12,
      sentAt: '11:22 AM',
      isOutgoing: true,
      status: 'delivered',
    },
  ],
};

export const STICKER_PACKS = [
  {
    id: 'gotcha',
    name: 'Gotcha',
    stickers: ['rocket', 'star', 'fire', 'party', 'heart', 'thumbs', 'wave', 'cool'],
  },
  {
    id: 'neon',
    name: 'Neon',
    stickers: ['bolt', 'moon', 'sun', 'ghost', 'cat', 'dog', 'coffee', 'pizza'],
  },
] as const;

export const STICKER_EMOJI: Record<string, string> = {
  rocket: '🚀',
  star: '⭐',
  fire: '🔥',
  party: '🎉',
  heart: '❤️',
  thumbs: '👍',
  wave: '👋',
  cool: '😎',
  bolt: '⚡',
  moon: '🌙',
  sun: '☀️',
  ghost: '👻',
  cat: '🐱',
  dog: '🐶',
  coffee: '☕',
  pizza: '🍕',
};

export const EMOJI_GRID = [
  '😀', '😂', '🥰', '😎', '🤔', '😴', '😭', '🤯',
  '👍', '👎', '🙏', '👋', '💪', '🤝', '✌️', '🫶',
  '❤️', '💙', '💜', '💚', '🔥', '⭐', '✨', '💯',
  '🎉', '🎊', '🏆', '🎯', '🚀', '⚡', '🌙', '☀️',
  '🍕', '☕', '🍺', '🌮', '🍣', '🍩', '🍦', '🥤',
  '🐶', '🐱', '🦊', '🐸', '🦄', '🐼', '🐧', '🦋',
];
